version: "3"
services:
  react-app:
    image: react-app
    build: ./frontend/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - piport
    volumes:
      - ./frontend/:/app/frontend
      - /app/frontend/node_modules

  api-server:
    image: api-server
    build: ./backend/
    ports:
      - "5000:5000"
    networks:
      - piport
    volumes:
      - ./backend/:/app/backend
      - /app/backend/node_modules
networks:
  piport:
    driver: bridge
# volumes:
