version: "3"
services:
  react-app:
    image: react-app
    build: ./frontend/
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - piport

  api-server:
    image: api-server
    build: ./backend/
    ports:
      - "5000:5000"
    networks:
      - piport

networks:
  piport:
    driver: bridge
# volumes:
